server:
  additionalApplications:
   - name: apps
     namespace: argocd
     project: default
     source:
       repoURL: https://github.com/irazzhivin/argocd-apps.git
       targetRevision: HEAD
       path: apps/
       directory:
         recurse: true
     destination:
       server: https://kubernetes.default.svc
     syncPolicy:
       automated:
         prune: false
         selfHeal: false