kind: Pod
apiVersion: v1
metadata:
  name: {{ .Release.Namespace }}-app
  labels:
    app: {{ .Release.Namespace }}
spec:
  containers:
    - name: {{ .Release.Namespace }}-app
      image: hashicorp/http-echo
      args:
        - "-text={{ .Values.text }}"



