apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: alpha-app-1
  namespace: argocd
spec:
  destination:
    namespace: app-1
    server: https://kubernetes.default.svc
  project: production
  source:
    helm:
      parameters:
      - name: version
        value: 3.193.1
      - name: application.enabled
        value: 'true'
      - name: clientType
        value: trial
      valueFiles:
      - values.yaml
    path: helm
    repoURL: https://github.com/irazzhivin/helm-chart-demo-app
    targetRevision: stable
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
