apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: beta-app-2
  namespace: argocd
spec:
  destination:
    namespace: app-2
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: version
        value: 3.193.1
      - name: application.enabled
        value: 'true'
      - name: clientType
        value: trial
      valueFiles:
      - values.yaml
    path: helm
    repoURL: https://github.com/irazzhivin/argocd-apps/
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
