apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: crossplane-aws-provider
  namespace: argocd
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: namespace
        value: crossplane-system
      - name: AWSRoleArn
        value: arn:aws:iam::478836649669:role/crossplane
      valueFiles:
      - values.yaml
    path: charts/crossplane-aws-provider
    repoURL: https://github.com/irazzhivin/argocd-apps/
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
