apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: crossplane
  namespace: argocd
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values:
        provider:
          packages:
            - provider-aws
      valueFiles:
      - values.yaml
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.9.0
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
